package com.epam.esm.dto.status;

public enum OrderOperationStatus {
    CREATED,
    NOT_ENOUGH_MONEY,
    TOTAL_PRICE_LARGER_THAN_10000,
    CERTIFICATES_ID_NOT_FOUND,
    CERTIFICATES_NOT_FOUND_AND_PRICE_LARGER_THAN_10000,
    INVALID_USER_INFO
}
